<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>aspnet-LitackaApi-65980935-d0e9-45b7-861e-00673dc619d1</UserSecretsId>
	</PropertyGroup>
	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.1" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.11.10" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="App_Data\" />
		<Folder Include="wwwroot\images\" />
	</ItemGroup>

</Project>
